version: '3.6'
services:
  reverse-proxy:
    # build: .
    image: docker.feddema.dev/reverse-proxy:latest
    # image: reverse-proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf # Pass nginx config file
      - /root/.acme.sh/:/etc/ssl/ # Pass letsencrypt keys
    container_name: reverse-proxy # Set container name
    
